config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do 
  devise_for :users
 
 root to: 'home#homepage'  
 get '/admin/users_count', to: 'admin#users_count'    
 resources :items do                # scaffolding RESTful actions
    get :upvote, on: :member        # new action; get - method,  
                                    # :upvote - method name, on: :member - получаем доступ к нему после id в адресной строке (относится к единственному объекту)   
    get :expensive, on: :collection # :collection относится к коллекции объектов
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_many :comments, as: :commentable 
#говорим что BlogPost является комментируемым (BlogPost type comments)
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user,  optional: true
    has_many :positions
    has_many :items, through: :positions

#has_and_belongs_to_many :items  (if we have carts_items table)
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true 
# полиморфная ассоциация комментируемы другие модели (item,blog_post) 
end

app/models/image.rb
class Image < ApplicationRecord
   belongs_to :imageable, polymorphic: true
end

app/models/item.rb
class Item < ApplicationRecord

# валидации 

validates :price, numericality: {greater_than: 0}
validates :name, presence: true

has_many :positions
has_many :carts, through: :positions
has_many :comments, as: :commentable  
has_one  :image, as: :imageable
# говорим что Item является комментируемым (Item type comments)

# has_and_belongs_to_many :carts (if we have carts_items table)
has_and_belongs_to_many :orders
# callbacks что происходит когда что-то создается.удаляется.случается

# after_initialize { p 'initialize' } 
# after_save       { p 'save'}        
# after_create     { p 'create'}
# after_update     { p 'update' }
# after_destroy    { p 'destroy' }

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :items

    def calculate_total

       write_attribute :total, items.map(&:price).inject(:+)

       # создаем дополнительный виртуальный аттрибут для этой модели
       # перебираем items, цены и + между собой 
    end
end

app/models/position.rb
class Position < ApplicationRecord
    belongs_to :cart
    belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
 
  devise :database_authenticatable, :registerable,         # Include default devise modules. Others available are :confirmable, 
         :recoverable, :rememberable, :validatable         # :lockable, :timeoutable, :trackable and :omniauthable
    has_one :cart, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :comments
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :admin?
    # layout 'admin'

    def users_count
        @users_count = User.count
        render layout: 'admin'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base       
    # если мы сюда что-то добавляем, это будет доступно в любом контроллере в нашем приложении

    def render_403
        render file: 'public/403.html', status: :forbidden
    end
    
    def render_404
        render file: 'public/404.html', status: :not_found
    end     

    def admin?
        render_403 unless params[:admin]
        #render 403, status: :forbidden unless params[:admin]
        # пока юзер админ (можно передать в params в адресной строке, НЕБЕЗОПАСНО,так не делают), если нет: доступ запрещен
        # current_user.admin
     end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def homepage
        render :home
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   
   # layout false                        # позволяет не отрендеривать лайауты
   skip_before_action :verify_authenticity_token
   # какое-то действие, использующееся во многих контроллерах перед 
   # действием самого контроллера (например, найти предмет, юзера или запись: find_item) 
   # или проверить админство (только админ может делать что-то) 
   before_action :find_item, only: %i[show edit update destroy upvote]   
   #before_action :admin?,    only: %i[edit]            
   after_action :show_info,  only: %i[index]

   
   def index                                  # показывает все что есть в базе данных   
      @items = Item.all.order(:id).includes :image 
      # @items = @items.includes(:image)        # пример жадной загрузки (eager loading)

      # примеры поиска по объектам через get (параметры передаются в адресной строке):
      # @items = @items.where('price >= ?', params[:price_from]) if params[:price_from]
      # @items = @items.where('created_at >= ?', 1.day.ago) if params[:today]
      # @items = @items.where('votes_count >= ?', params[:votes_from]) if params[:votes_from]                      
   end

   def create                          # создание одного объекта в базу
      @item = Item.create(items_params)
      if @item.persisted?
         flash[:success] = 'Item was saved'
      redirect_to items_path
     else
      flash.now[:error] = 'Please fill all fields correctly'
      render :new
     end
   end

# RESTful cotrollers (+create)           # show, index - endpoints

   def new                     # рендерит форму которая потом будет посылаться в метод create
      @item = Item.new
   end
                                                                
   #def show                  # показывает один по текущему id                                         
      #render body: 'Page not found', status: 404 unless @item - не нужно так как активирована 404 страница в public
     #end                                                             

   def update                          
      if @item.update(items_params)
         flash[:success] = 'Item was updated'
      redirect_to items_path
      else
         flash.now[:error] = 'Please fill all fields correctly'
         render json: @item.errors, status: :unprocessable_entity
      end
   end                                                           

   #def edit             # при вызове посылается на update
      #render body: 'Page not found', status: 404 unless @item - не нужно так как активирована 404 страница в public
   #end                                                 
                                                                 

   def destroy                        # уничтожает объект
      if @item.destroy.destroyed?
         flash[:success] = 'Item has been deleted'
         # render json: { success: true }
         redirect_to items_path
         # redirect_to '/items'
         # redirect_to 'items/index'   # при рендере (в отличие от редиректа)не происходит 
      else                             # перезагрузки страницы и мы теряем доступ к переменной @items
         flash[:error] = "Item wasn't deleted"
         render json: item.errors, status: :unprocessable_entity   
      end   
   end     
   
   def upvote
       @item.increment! :votes_count   # увеличиваем на 1 поле votes
       redirect_to items_path
   end

   def expensive
       @items = Item.where('price > 1000')
       render :index
   end

   private

   def items_params
      params.require(:item).permit(:name, :price, :description)
   end
      
   def find_item
      # найди айтем у которого ид равен ид айтема который мы передали в парамсах; верни не как массив, а первый элемент
      @item = Item.where(id: params[:id]).first  
      render_404 unless @item 
   end

   def show_info
      puts 'Index endpoint'
   end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def urls_to_content(str)
     str.gsub!(%r{https://[^\s<]+}) do |url|        #регулярка для url картинки
        if url[/(?:png|jpe?g|gif|svg)$/]
            "<img src='#{url}' width='100'; />"
        else
            "<a href='#{url}' target='_blank'> link to info</a>"
     end
  end
 str.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
<div style="margin: 0 auto">
  <p>Count users:
    <%= @users_count %>
    on this site.
  </p>
</div>

app/views/home/home.html.erb
<!DOCTYPE html>
<html>
  <%= stylesheet_link_tag "home", media: "all" %>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <div class="container">
      <%= button_to 'into shop', items_path, method: :get, class: "animated-word" %>
    </div>
    <div class="container">
      <% if user_signed_in? %>                                               <!-- devise -->
        <a href="#" class="btn btn-light">
          Добро пожаловать,
          <%= current_user.email %>
        </a>
        <%= link_to 'Выход', destroy_user_session_path,
                    method: :get,
                    class: "btn btn-light" %>
        <%= link_to 'Редактирование', edit_user_registration_path,
                    class: "btn btn-light" %>
      <% else %>
        <%= link_to 'Вход', new_user_session_path,
                    class: "btn btn-light" %>
        <%= link_to 'Регистрация', new_user_registration_path,
                    class: "btn btn-light" %>
      <% end %>
    </div>
  </body>
</html>

app/views/items/edit.html.erb
<!DOCTYPE html>
<html>
  <div class="col-sm-12 my-auto">
    <h2 style="color: #B00100; margin: 0 auto">edit
      <%= @item.name.camelize %></h2>
    <br/>

    <%= simple_form_for @item do |f| %>
      <!-- post in database -->
      <div class="form-group row">
        <div class="col-sm-10">
          <%= f.input :name, input_html: {class: "form-control form-control-sm", id:"colFormLabelSm"} %>
        </div>
        <div class="col-sm-10">
          <%= f.input :price, input_html: {class: "form-control form-control-sm", id:"colFormLabelSm"}, required: true %>
        </div>
        <div class="col-sm-10">
          <%= f.input :description, label: t("item.description"), input_html: {class: "form-control form-control-sm", id:"colFormLabelSm"} %>
          <!-- Transleted into RU by /config/locales/ru.yml -->
        </div>
        <div class="col-sm-10">
          <%= f.button :submit, class: " btn btn-secondary", style: "margin-top: 15px" %>
          <!-- Save button -->
        </div>
      </div>
    <% end %>

    <%= render partial: 'shared/email' %>
    <!-- render method; partials file name starts _ to distinguish them from
    regular views, but referred to without the underscore -->
  </div>
</html>

app/views/items/index.html.erb
<!DOCTYPE html>
<html>
<%= stylesheet_link_tag "items", media: "all" %>
<h2 style="color: #B00100; margin: 0 auto">All items</h2> <br/>
<% if @items.empty? %>
<h3 style="color: #B00100; margin: 0 auto">NO ITEMS!</h3> <br/>
<%= button_to 'new item', new_item_path, method: :get %>
<% else %>
<table class="table table-hover table-dark", style="border: 3px double black">
<thead>
  <tr>
  <th scope="col">Id</th>
  <th scope="col">Name</th>
  <th scope="col">Price</th>
  <th scope="col">Description</th>
  <th scope="col">Rating</th>
  <th scope="col">Image</th>
  <th scope="col">Delete</th>
  </tr>
 </thead> 
<% @items.each do |item| %>                           
      <tbody> 
      <tr data-item_id="<%= item.id %>">
   <th scope="col"><%= item.id %></th>
   <th scope="col"><%= link_to item.name, item_path(item) %></th>    <!-- переход по ссылке на страницу item -->
   <th scope="col"><%= item.price %></th> 
   <th scope="col"><%= item.description %></th> 
   <th scope="col"><%= item.votes_count %> &nbsp; <%= link_to '+', upvote_item_path(item), class: "text-info" %></th> 
   <th scope="col"><%= !item.image.nil? ? image_tag(item.image.file, width: '30px', height: '30px') : 'no img' %></th>
   <th scope="col"><%= button_to 'delete', item_path(item), method: :delete, class: "deleteAction" %></th>
      </tr>
      </tbody>  
<% end %> 
</table>

<div class="btn-toolbar mb-3" role="toolbar" aria-label="Toolbar with button groups">
 <div class="btn-group mr-2" role="group" aria-label="First group">

<%= button_to 'new item', new_item_path, method: :get, class: "btn btn-secondary", style: "margin-right 15px" %>
<br/>
<%= button_to 'only expensive', expensive_items_path, method: :get, class: "btn btn-secondary", style: "margin-right 15px" %>
<br/>
<%= button_to 'index', items_path, method: :get, class: "btn btn-secondary", style: "margin-right 15px" %>
<br/>
<%= button_to 'admin panel', admin_users_count_path, method: :get, class: "btn btn-secondary", style: "margin-right 15px" %>
 </div>
</div> 
<%= button_to 'home', root_path, method: :get, class: "btn btn-secondary", style: "margin-right 15px" %>
<% end %>

<%= render partial: 'shared/email' %>
</html>

app/views/items/new.html.erb
<!DOCTYPE html>
<html>
  <div class="col-sm-12 my-auto">
    <h2 style="color: #B00100; margin: 0 auto">create new item</h2>
    <br/>
    <!--
    <form action="/items/new" method="post">
      <label>
        <input type="text" name="title"/>
      </label>
      <input type="submit"/>
    </form>

    --> <!-- post in database. using Gem Simple Form -->
    <%= simple_form_for @item do |f| %>
      <div class="form-group row">
        <div class="col-sm-10">
          <%= f.input :name, input_html: {class: "form-control form-control-sm", id:"colFormLabelSm"} %>
        </div>
        <div class="col-sm-10">
          <%= f.input :price, input_html: {class: "form-control form-control-sm", id:"colFormLabelSm"}, required: true %>
        </div>
        <div class="col-sm-10">
          <%= f.input :description, label: t("item.description"), input_html: {class: "form-control form-control-sm", id:"colFormLabelSm"} %>
          <!-- Transleted into RU by /config/locales/ru.yml -->
        </div>
        <div class="col-sm-10">
          <%= f.button :submit, class: " btn btn-secondary", style: "margin-top: 15px" %>
          <!-- Save button -->
        </div>
      </div>
    <% end %>

    <%= render partial: 'shared/email' %>

  </div>
</html>

app/views/items/show.html.haml
%h2{ style: "color: #B00100; margin: 0 auto" } show item 
%br

%h4= @item.name.upcase

%ul
  %li Price:       #{@item.price} $
  %li Weight:      #{@item.weight} kg
  %li Description: #{urls_to_content(@item.description)}

%br

= button_to "edit #{@item.name}", edit_item_path, method: :get 
%br
= button_to "delete #{@item.name}", item_path(@item), method: :delete 
%br
= button_to "index", items_path, method: :get 
%br

= render partial: 'shared/email' 

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    >
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron vertical-center">
      <div class="container">
        <h4 style="color:#B00100;">
          Admin Panel</h4>
        <%= yield %>
        <%= render partial: 'shared/email' %>
      </div>
    </div>
  </body>
  <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"
  ></script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    >
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron vertical-center">
      <div class="container">
        <%= render 'auth/notification' %>
        <%= yield %>
      </div>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/views/shared/_email.html.erb
<!-- Это кусок кода (_partial), который вставляется в многие другие страницы
одной строкой, чтобы не плодить код -->
<div class="email" style="font-size: 12px; font-weight: bold; margin: 20px">
  <p>По всем вопросам пишите на почту:</p>
  <%= mail_to 'dkrestt@gmail.com',
              'DKrestt@gmail.com',
     { style: 'color: brown;' } %>
</div>